export const SIGNUP_REQUESTING = 'SIGNUP_REQUESTING'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'

export const LOGIN_REQUESTING = 'LOGIN_REQUESTING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_EXISTING = 'LOGIN_EXISTING'
export const LOGOUT = 'LOGOUT'

export const CLIENT_SET = 'CLIENT_SET'
export const CLIENT_UNSET = 'CLIENT_UNSET'

export const LOAD_IDIOMS = "LOAD_IDIOMS";
export const LOADED_IDIOMS = "LOADED_IDIOMS";

export const LOAD_CLASSIFYLIST = "LOAD_CLASSIFYLIST";
export const LOADED_CLASSIFYLIST = "LOADED_CLASSIFYLIST";

export const ADD_CLASSIFY = "ADD_CLASSIFY";
export const ADDED_CLASSIFY = "ADDED_CLASSIFY";

export const ADD_IDIOM = "ADD_IDIOM";
export const ADDED_IDIOM = "ADDED_IDIOM";

export const UPDATE_IDIOM = "UPDATE_IDIOM";
export const UPDATED_IDIOM = "UPDATED_IDIOM";

export const DELETE_IDIOM = "DELETE_IDIOM";
export const DELETED_IDIOM = "DELETED_IDIOM";

export const CHANGE_CATEGORY = "CHANGE_CATEGORY";

// Server URL
export const SERVER_ADDRESS = "http://192.168.1.105:3808/api/";